export const designTokens = {
  color: {
    background: '#F7F8FA',
    textPrimary: '#191B1D',
    textSecondary: '#51565C',
    textTertiary: '#9AA0A6',
    actionPrimary: '#191B1D',
    actionDisabled: '#9AA0A6',
    cardSurface: '#FFFFFF',
    categoryFunctional: '#C6EBEE',
    categoryYoga: '#E5DBF5',
    categoryRumba: '#F5EDAE',
    categorySpinning: '#D8F3E5',
    destructiveText: '#8C1D24',
    destructiveSurface: '#FCE7EA',
    successText: '#1F5C2C',
    successSurface: '#DCEFE0',
    pixelAccent: '#A8B2BB',
    instructorPalette: [
      '#F5C2A0',
      '#A0D8E5',
      '#D8A0E5',
      '#E5D8A0',
      '#A0E5B8',
      '#E5A0A0',
      '#A0A8E5',
      '#C2D8A0',
    ] as const,
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 40,
  },
  tabBarHeight: 88,
  radius: {
    control: 12,
    card: 24,
    pill: 999,
    avatar: 999,
  },
  fontSize: {
    eyebrow: 10,
    label: 12,
    caption: 13,
    body: 14,
    bodyLg: 16,
    title: 20,
    display: 32,
    hero: 36,
  },
} as const;

export type DesignTokens = typeof designTokens;
